### ISSUE TITLE
Add valid style on input

### ISSUE THREAD

**Issue by srngch** [srngch/react-signup-form#22]
```css
.input-wrapper.valid input {
  border-color: var(--open-color-blue);
}
```

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
